name: Deploy Storybook to GH pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm i
    - name: Install deploy-storybook
      run: npm i -g @storybook/storybook-deployer
    - name: Build and deploy
      run: storybook-to-gh-pages -- --ci --branch=gh-pages
